---
kind: pipeline
type: docker
name: default

trigger:
  ref:
    - refs/heads/trunk
    - refs/pull/**
    - refs/tags/**

volumes:
    - name: docker_sock
      host:
        path: /var/run/docker.sock
    - name: root_home
      host:
        path: /root

steps:
  - name: build
    image: registry.digitalocean.com/unison-lang/docker-builder:1
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
      - name: root_home
        path: /root
    
    commands:
      - make build-haskell-builder
      - make push-haskell-builder
