---
kind: pipeline
type: docker
name: default

trigger:
  ref:
    - refs/heads/trunk
    - refs/pull/**
    - refs/tags/**

volumes:
    - name: docker_sock
      host:
        path: /var/run/docker.sock
    - name: root_home
      host:
        path: /root

steps:
  - name: build
    image: plugins/docker
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
      - name: root_home
        path: /root
    
    commands:
      - cd haskell-build
      - docker build -t registry.digitalocean.com/stewcasa/haskell-build:$DRONE_BUILD_NUMBER .
      - docker push registry.digitalocean.com/stewcasa/haskell-build:$DRONE_BUILD_NUMBER 
